# -*- coding: utf-8 -*-
"""Ai-Labs-Week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x71UnQ4oXkftkPwdvK_RNzOHzkFnoxlh

## Training Data
"""

x=[1,2,4]
y=[1,3,3]

#Create a trainingData vector made of (xi,yi) values
trainingData = []
for i in range(len(x)):
    trainingData.append((x[i],y[i]))
print(trainingData)

"""## Feature extractor"""

def phi(x):
  return (1,x)

"""## Loss function"""

import numpy as np
def trainLoss(w):
  sum = 0
  for num in range(len(trainingData)):
    sum += (np.dot(phi(trainingData[num][0]),w) - trainingData[num][1])**2
  loss = (1/len(trainingData)*sum)
  print(loss)
  return loss

"""### Test 1

"""



loss = trainLoss([0.00005,0.0002])
print("The loss is: ", loss)