# -*- coding: utf-8 -*-
"""Labs-3.2-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14e5mpXFng4rdpi9P_Gi0f7_WMCdLvDhI
"""

def multiplicationTable(num):
  for i in range(1,num+1):
    for j in range(1,num+1):
      print(i,"x",j,"=",i*j)

number = int(input("Enter a number: "))
multiplicationTable(number)

def isPrime(num):
  for i in range(2,num):
    if num%i==0:
      return False
  return True

number = int(input("Enter a number: "))
if isPrime(number):
  print(number,"is a prime number")
else:
  print(number,"is not a prime number")

def findFactorial(num):
  factorial = 1
  for i in range(1,num+1):
    factorial *= i
  return factorial

number = int(input("Enter a number: "))
print("Factorial of",number,"is",findFactorial(number))

class Chatbot():
  def __init__(self):
    self.options = {"Hi": "Hello", "How are you?": "I am fine", "What is your name?": "My name is Chatbot"}

  def chat(self):
    while True:
      user_input = input("You: ")
      if user_input in self.options:
        print("Chatbot: ",self.options[user_input])
      elif user_input.lower() == "bye":
        print("Chatbot: Bye")
        break
      else:
        print("Chatbot: Sorry, I don't understand")

chatbot = Chatbot()
chatbot.chat()