# -*- coding: utf-8 -*-
"""Week2-Labs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3J1eEFSdQGW74PiC2lbXaJhUXcDkB9Y
"""

string = input("Enter a string: ")
string_length = len(string)

for num in range(0, string_length, 2):
    #print(num)
    print(string[num])

string = input("Enter a string: ")
n = int(input("Enter a number: "))
print(string[n:])

myList = []
for num in range(0, 5):
    num = int(input("Enter a number: "))
    myList.append(num)
if myList[0] == myList[-1]:
    print("True")
else:
    print("False")

